spring.application.name=PESocial
spring.data.mongodb.uri=mongodb://localhost:27017/pesocial

app.jwt.secret=change-this-very-long-secret-key-for-production-1234567890
app.jwt.access-expiration-seconds=900
app.jwt.refresh-expiration-seconds=604800

app.monetization.platform-commission=0.20
app.monetization.payout-threshold=50

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
